openapi: 3.1.0
info:
  title: Insurance Policy API
  description: API for managing insurance policy data including policy details, transmission, agents, parties, funding, and more.
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/Insured-Retirement-Institute/Pending-Case/blob/initial-draft-revision-20250429/LICENSE

paths:
  /v1/applications/{applicationId}/activity-status:
    parameters:
          - name: applicationId
            in: path
            required: true
            schema:
              type: string
    get:
      operationId: getActivityStatusByApplicationId
      summary: Retrieve activity status of an application
      description: Retrieve all activity related to the status details of an application.
      
      responses:
        "200":
          description: Application activity status successfully retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActivityStatusDetail"
  /v1/policies/{policyNumber}/activity-status:
    parameters:
          - name: policyNumber
            in: path
            required: true
            schema:
              type: string
    get:
      operationId: getActivityStatusByPolicyNumber
      summary: Retrieve activity status of a policy
      description: Retrieve all activity related to the status details of a policy.
      
      responses:
        "200":
          description: Policy activity status successfully retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActivityStatusDetail"
components:
  schemas:
    IndividualIdentity:
      type: object
      properties:
        type:
          type: string
          const: individual
        firstName:
          type: string
        middleName:
          type: string
        lastName:
          type: string
        taxId:
          type: string
    IndividualProducer:
      allOf:
        - $ref: "#/components/schemas/IndividualIdentity"
        - type: object
          properties:
            npn:
              type: string
            crdNumber:
              type: string
            relationships:
              type: array
              items:
                type: string
                enum:
                  - primaryAgent
                  - secondaryAgent
                  - additionalAgent
                  - investmentAdvisorRepresentative
    IndividualParty:
      type: object
      allOf:
        - $ref: "#/components/schemas/IndividualIdentity"
        - $ref: "#/components/schemas/PartyRelationship"
    EntityIdentity:
      type: object
      properties:
        type:
          type: string
          const: entity
        name:
          type: string
        taxId:
          type: string
    EntityProducer:
      type: object
      allOf:
        - $ref: "#/components/schemas/EntityIdentity"
        - type: object
          properties:
            npn:
              type: string
            crdNumber:
              type: string
            relationships:
              type: array
              items:
                type: string
                enum:
                  - brokerageGeneralAgency
                  - registeredInvestmentAdvisoryFirm
                  - independentMarketingOrganization
    EntityParty:
      type: object
      allOf:
        - $ref: "#/components/schemas/EntityIdentity"
        - $ref: "#/components/schemas/PartyRelationship"
    PartyRelationship:
      type: array
      items:
        type: string
        enum:
          - owner
          - jointOwner
          - annuitant
          - jointAnnuitant
          - primaryBeneficiary
          - contingentBeneficiary
    ActivityStatusDetail:
      description: Defines the schema for Activity Status Detail
      type: object
      properties:
        correlationId:
          type: string
        policyNumber:
          type: string
        applicationOrigin:
          type: object
          properties:
            platform:
              type: string
            isElectronic:
              type: boolean
            id:
              type: string
        cusip:
          type: string
        status:
          type: string
          enum: [received, inProgress, completed, cancelled]
        isActionNeeded:
          type: boolean
        signedDate:
          type: string
          format: date
        receivedDate:
          type: string
          format: date
        issuedDate:
          type: string
          format: date
        effectiveDate:
          type: string
          format: date
        rateEffectiveDate:
          type: string
          format: date
        fundsHeldUntilDate:
          type: string
          format: date
        cancellation:
          type: object
          properties:
            initiator:
              type: string
              enum: [advisor, carrier, client]
            cancelledDate:
              type: string
              format: date
            reason:
              type: string
        producers:
          type: array
          items:
            anyOf:
              - $ref: "#/components/schemas/IndividualProducer"
              - $ref: "#/components/schemas/EntityProducer"
        parties:
          type: array
          items:
            anyOf:
              - $ref: "#/components/schemas/IndividualParty"
              - $ref: "#/components/schemas/EntityParty"
        delivery:
          type: object
          properties:
            sentDate:
              type: string
              format: date
            method:
              type: string
              enum:
                - fedex
                - ups
                - electronicDelivery
                - handDelivery
                - usps
            trackingNumber:
              type: string
        caseManager:
          type: object
          properties:
            fullName:
              type: string
            phoneNumber:
              type: string
            emailAddress:
              type: string
            websiteURL:
              type: string
        canSellValidation:
          type: object
          properties:
            status:
              type: string
              enum: [awaitingReview, inProgress, completed]
            isActionNeeded:
              type: boolean
            startDate:
              type: string
              format: date
            endDate:
              type: string
              format: date
            note:
              type: string
            issues:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                    enum:
                      - trainingIncompleteMissing
                      - trainingExpired
                      - agentNotAppointedForSale
                      - jitAppointmentInProgress
                      - agentNotLicensed
                      - other
                  note:
                    type: string
                  affectedProducer:
                    type: object
                    properties:
                      npn:
                        type: string
                      crdNumber:
                        type: string
                      taxId:
                        type: string
        documentReview:
          type: object
          properties:
            status:
              type: string
              enum: [awaitingReview, inProgress, completed]
            isActionNeeded:
              type: boolean
            startDate:
              type: string
              format: date
            endDate:
              type: string
              format: date
            note:
              type: string
            issues:
              type: array
              items:
                type: object
                properties:
                  reason:
                    type: string
                    enum:
                      - applicationIssue
                      - contactCarrier
                      - incompleteForm
                      - missingForm
                      - missingSignature
                      - needClarity
                      - other
                  formName:
                    type: string
                  formNumber:
                    type: string
                  dueDate:
                    type: string
                    format: date
                  note:
                    type: string
        suitability:
          type: object
          properties:
            status:
              type: string
              enum: [awaitingReview, inProgress, completed, notApplicable]
            isActionNeeded:
              type: boolean
            startDate:
              type: string
              format: date
            endDate:
              type: string
              format: date
            reason:
              type: string
              enum:
                - moreInformationNeeded
                - notSuitableForClient
                - other
            note:
              type: string
            dueDate:
              type: string
              format: date
        funding:
          type: object
          properties:
            startDate:
              type: string
              format: date
            endDate:
              type: string
              format: date
            isActionNeeded:
              type: boolean
            status:
              type: string
              enum: [awaitingReview, inProgress, completed]
            note:
              type: string
            sources:
              type: array
              items:
                type: object
                properties:
                  method:
                    type: string
                    enum:
                      - anotherPolicy
                      - check
                      - clearinghouse
                      - creditCard
                      - debitCard
                      - digitalPayment
                      - electronicFundTransfer
                      - payrollDeduction
                      - wireTransfer
                  type:
                    type: string
                    enum:
                      - contribution
                      - directRollover
                      - employeeContribution
                      - employerContribution
                      - full1035Exchange
                      - indirectRollover
                      - nonQualifiedTransferOfAssets
                      - partial1035Exchange
                      - qualifiedTransfer
                  isActionNeeded:
                    type: boolean
                  anticipatedAmount:
                    type: number
                    format: float
                  receivedAmount:
                    type: number
                    format: float
                  receivedDate:
                    type: string
                    format: date
                  status:
                    type: string
                    enum: [inProgress, complete]
                  reason:
                    type: string
                    enum:
                      - awaitingFundsFromCedingCompany
                      - contactTheCarrier
                      - fundingDiscrepancy
                      - nigoAtCedingCarrier
                      - noFundsReceivedCash
                      - pendingReg60
                      - other
                  effectiveDate:
                    type: string
                    format: date
                  note:
                    type: string
                  cedingCompany:
                    type: object
                    properties:
                      name:
                        type: string
                      accountNumber:
                        type: string
                      startDate:
                        type: string
                        format: date
                      referenceNumber:
                        type: string
                      nextActivityDate:
                        type: string
                        format: date
                      note:
                        type: string
